radeon i xorg 1.18

diff --git a/grafiki b/grafiki
--- a/grafiki
+++ b/grafiki
@@ -149,22 +149,27 @@ if [ "$1" = "nvidia" ]; then
 		fi
 	fi
 elif [ "$1" = "radeon" ]; then
-	if [ "$(lspci | grep VGA | awk '{print tolower($0)}' | grep radeon)" = "" ] || [ "$(glxinfo | grep 'AMD Radeon HD' | sed -e 's/.*HD //g' -e 's/ .*//g')" -le 5000 ]; then
-		dymek -i $warning1 "$TEXT_UWAGA" "$TEXT_STEROWNIKI3"
+	#sprawdzanie xorga
+	if [ "$cat /var/log/Xorg.0.log | grep 'X.Org X Server' | grep '18')" != "" ];then
+		dymek -i $warning1 "$TEXT_UWAGA" "$TEXT_STEROWNIKI4"
 	else
-		if [ -e /tmp/netext73/sumy/sumy_kontrolne.txt ]; then
-		    grep fglrx_ /tmp/netext73/sumy/sumy_kontrolne.txt | sed 's/.deb//' | awk '{print $2}' | sort -r > 2a.txt
-		    lista=$(cat 2a.txt | tr '\n' '!' | sed -e '$s/!$//g' )
-		    ster=$(yad --center --title="$nazwa_skryptu" --width=$((310*$skala)) --window-icon="/opt/NeteXt73/ikony/radeon.png" --image="/opt/NeteXt73/ikony/radeon.png" --text="$TEXT_STEROWNIKI2 <span color=\"$kolor_textu\"><b>Radeon</b></span>" --form --field="$TEXT_STEROWNIK:CB" "$lista" --button="gtk-ok:0" --button="$TEXT_POWROT:1")
-			klawisz=$?; ster=$(echo $ster | cut -d "|" -f 1)
-			if [ "$ster" != "" ] && [ "$klawisz" = "0" ]; then
-				ster1=$(echo $ster.deb | sed "s/fglrx/fglrx-amdcccle/")
-				ster2=$(echo $ster.deb | sed "s/fglrx/fglrx-core/")
-				yad_wget $adres_sterownikow/$ster.deb $adres_sterownikow/$ster1 $adres_sterownikow/$ster2
-				if [ -e $ster.deb ] && [ -e $ster1 ] && [ -e $ster2 ] && [ "$(grep $(md5sum $ster.deb) $sumy_kontrolne)" != "" ] && [ "$(grep $(md5sum $ster1) $sumy_kontrolne)" != "" ] && [ "$(grep $(md5sum $ster2) $sumy_kontrolne)" != "" ]; then
-					instaluj_RADEON
-				else
-					yad --center --error --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0" --title="$nazwa_skryptu"  --text="$TEXT_SUMA_KONTROLNA"
+		if [ "$(lspci | grep VGA | awk '{print tolower($0)}' | grep radeon)" = "" ] || [ "$(glxinfo | grep 'AMD Radeon HD' | sed -e 's/.*HD //g' -e 's/ .*//g')" -le 5000 ]; then
+			dymek -i $warning1 "$TEXT_UWAGA" "$TEXT_STEROWNIKI3"
+		else
+			if [ -e /tmp/netext73/sumy/sumy_kontrolne.txt ]; then
+			    grep fglrx_ /tmp/netext73/sumy/sumy_kontrolne.txt | sed 's/.deb//' | awk '{print $2}' | sort -r > 2a.txt
+			    lista=$(cat 2a.txt | tr '\n' '!' | sed -e '$s/!$//g' )
+			    ster=$(yad --center --title="$nazwa_skryptu" --width=$((310*$skala)) --window-icon="/opt/NeteXt73/ikony/radeon.png" --image="/opt/NeteXt73/ikony/radeon.png" --text="$TEXT_STEROWNIKI2 <span color=\"$kolor_textu\"><b>Radeon</b></span>" --form --field="$TEXT_STEROWNIK:CB" "$lista" --button="gtk-ok:0" --button="$TEXT_POWROT:1")
+				klawisz=$?; ster=$(echo $ster | cut -d "|" -f 1)
+				if [ "$ster" != "" ] && [ "$klawisz" = "0" ]; then
+					ster1=$(echo $ster.deb | sed "s/fglrx/fglrx-amdcccle/")
+					ster2=$(echo $ster.deb | sed "s/fglrx/fglrx-core/")
+					yad_wget $adres_sterownikow/$ster.deb $adres_sterownikow/$ster1 $adres_sterownikow/$ster2
+					if [ -e $ster.deb ] && [ -e $ster1 ] && [ -e $ster2 ] && [ "$(grep $(md5sum $ster.deb) $sumy_kontrolne)" != "" ] && [ "$(grep $(md5sum $ster1) $sumy_kontrolne)" != "" ] && [ "$(grep $(md5sum $ster2) $sumy_kontrolne)" != "" ]; then
+						instaluj_RADEON
+					else
+						yad --center --error --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0" --title="$nazwa_skryptu"  --text="$TEXT_SUMA_KONTROLNA"
+					fi
 				fi
 			fi
 		fi
