czyszczenie kodu

diff --git a/kernele b/kernele
--- a/kernele
+++ b/kernele
@@ -11,10 +11,10 @@
 #		   				| |\  |  __/ |_  __//  \| |_    / /  ___) |
 #		   				|_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
 #
-#  __  ___ _______   ____ __  __  _   _ ___  __ _____ __  ___    ____   __ __ _____ ___ __ __ _  _ 
+#  __  ___ _______   ____ __  __  _   _ ___  __ _____ __  ___    ____   __ __ _____ ___ __ __ _  _
 # /__\| _,\_   _\ `v' /  V  |/  \| | | |_  |/  \_   _/__\| _ \ /' _| `v' /' _/_   _| __|  V  | || |
 #| \/ | v_/ | |  `. .'| \_/ | /\ | |_| |/ /| /\ || || \/ | v / `._`.`. .'`._`. | | | _|| \_/ | \/ |
-# \__/|_|   |_|   !_! |_| |_|_||_|___|_|___|_||_||_| \__/|_|_\ |___/ !_! |___/ |_| |___|_| |_|\__/ 
+# \__/|_|   |_|   !_! |_| |_|_||_|___|_|___|_||_||_| \__/|_|_\ |___/ !_! |___/ |_| |___|_| |_|\__/
 #
 #            __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
 #       ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
@@ -92,131 +92,131 @@ if [ "$klawisz" = "4" ]; then
 fi
 
 rodzaj=$(echo $kern | cut -d " " -f 1 | awk '{print tolower($0)}')
-	#lokalne
-	if [ "$kern" = "$TEXT_MENU_INSTALATOR3" ]; then
-		a=$(yad --center --on-top --file-selection --filename="$download/" --title="$(echo $TEXT_DEB1 | sed 's/headers/headers ext73 /' | sed 's/image/image ext73 /')" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --width=$((750*$skala)) --height=$((450*$skala)) --button="gtk-ok:0" --button="$TEXT_POWROT:1")
-		if [ $? = 0 ]; then
-			if [ "$(echo $a | grep 'linux-image' | grep 'ext' | grep '.deb')" != "" ]; then
-				cd $(echo $a | sed -e 's/linux.*//g');     b=$(echo $a | sed -e 's/linux-image/linux-headers/g')
-				echo "tak" > /tmp/netext73/ok.txt
-			elif [ "$(echo $a | grep 'linux-headers' | grep 'ext' | grep '.deb')" != "" ]; then
-				cd $(echo $a | sed -e 's/linux.*//g');     b=$(echo $a | sed -e 's/linux-headers/linux-image/g')
-				echo "tak" > /tmp/netext73/ok.txt
-			else
-				yad --center --error --title="$nazwa_skryptu" --text="$(echo $TEXT_DEB1 | sed 's/:/!/' | sed 's/headers/headers ext73 /' | sed 's/image/image ext73 /')" --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0"  --timeout=15 
-				echo "nie" > /tmp/netext73/ok.txt
-			fi
-			if [ "$(cat /tmp/netext73/ok.txt)" = "tak" ]; then
-				rm /tmp/netext73/kernel -fr; 	mkdir /tmp/netext73/kernel
-				cd /tmp/netext73/kernel; 	cp $a $b /tmp/netext73/kernel/
-				naglowek > instaluj.sh
-				#sprawdz_gcc >> instaluj.sh
-				instaluj_kernel >> instaluj.sh
-				instalacja2
-				cd /tmp/netext73; rm -rf kernel
-				restart
-			fi
-		fi
-	#tylko nagłówki
-	elif [ "$kern" = "$TEXT_MENU_INSTALATOR4" ]; then
-		a=$(yad --center --on-top --file-selection --filename="$download/" --title="$(echo $TEXT_DEB1 | sed 's/lub linux-image//' | sed 's/headers/headers ext73/')" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --width=$((750*$skala)) --height=$((450*$skala)) --button="gtk-ok:0" --button="$TEXT_POWROT:1")
-		if [ $? = 0 ]; then
+#lokalne
+if [ "$kern" = "$TEXT_MENU_INSTALATOR3" ]; then
+	a=$(yad --center --on-top --file-selection --filename="$download/" --title="$(echo $TEXT_DEB1 | sed 's/headers/headers ext73 /' | sed 's/image/image ext73 /')" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --width=$((750*$skala)) --height=$((450*$skala)) --button="gtk-ok:0" --button="$TEXT_POWROT:1")
+	if [ $? = 0 ]; then
 		if [ "$(echo $a | grep 'linux-image' | grep 'ext' | grep '.deb')" != "" ]; then
-			cd $(echo $a | sed -e 's/linux.*//g');	b=$(echo $a | sed -e 's/linux-image/linux-headers/g')
-			rm /tmp/netext73/kernel -fr; 	mkdir /tmp/netext73/kernel
-			cd /tmp/netext73/kernel;    	cp $b /tmp/netext73/kernel/
-			xterm -T instalator -e bash -c "/usr/bin/yes | sudo dpkg -i linux-headers*"
-		        restart
+			cd $(echo $a | sed -e 's/linux.*//g');     b=$(echo $a | sed -e 's/linux-image/linux-headers/g')
+			echo "tak" > /tmp/netext73/ok.txt
 		elif [ "$(echo $a | grep 'linux-headers' | grep 'ext' | grep '.deb')" != "" ]; then
-			cd $(echo $a | sed -e 's/linux.*//g')
-			rm /tmp/netext73/kernel -fr; 	mkdir /tmp/netext73/kernel
-			cd /tmp/netext73/kernel;		cp $a /tmp/netext73/kernel/
-			xterm -T instalator -e bash -c "/usr/bin/yes | sudo dpkg -i linux-headers*"
-			restart
+			cd $(echo $a | sed -e 's/linux.*//g');     b=$(echo $a | sed -e 's/linux-headers/linux-image/g')
+			echo "tak" > /tmp/netext73/ok.txt
 		else
-			yad --center --error --title="$nazwa_skryptu"  --text="$(echo $TEXT_DEB1 | sed -e 's/:/!/' -e 's/lub linux-image//' -e 's/headers/headers ext73 /')" --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0"  --timeout=15
+			yad --center --error --title="$nazwa_skryptu" --text="$(echo $TEXT_DEB1 | sed 's/:/!/' | sed 's/headers/headers ext73 /' | sed 's/image/image ext73 /')" --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0"  --timeout=15 
+			echo "nie" > /tmp/netext73/ok.txt
 		fi
+		if [ "$(cat /tmp/netext73/ok.txt)" = "tak" ]; then
+			rm /tmp/netext73/kernel -fr; 	mkdir /tmp/netext73/kernel
+			cd /tmp/netext73/kernel; 	cp $a $b /tmp/netext73/kernel/
+			naglowek > instaluj.sh
+			#sprawdz_gcc >> instaluj.sh
+			instaluj_kernel >> instaluj.sh
+			instalacja2
+			cd /tmp/netext73; rm -rf kernel
+			restart
 		fi
-	#kernele PPA
-	elif [ "$kern" = "$TEXT_MENU_INSTALATOR5" ]; then
-		cd /tmp/netext73; rm *.html -f
-		strona="http://kernel.ubuntu.com/~kernel-ppa/mainline/"
-		WERSJA_DISTRO=$(yad --center --on-top --title="$nazwa_skryptu" --width=$((420*$skala)) --window-icon="/opt/NeteXt73/ikony/linux.png" --text="$TEXT_PPA_1 <span color=\"$kolor_textu\">$WERSJA_UBUNTU</span>" --form --field="$TEXT_RODZAJ_SYSTEMU:CB"  "$wersje_ubu" --button="gtk-ok:0" --button="$TEXT_POWROT:1")
-		klawisz=$?; export WERSJA_DISTRO=$(echo $WERSJA_DISTRO | cut -d "|" -f 1)
-		if [ "$klawisz" = 0 ];then
-			wget $strona  2>&1 | pobieranie 
-			a=$(yad --center --height=$((630*$skala)) --width=$((410*$skala)) --button="gtk-ok:0" --button="$TEXT_POWROT:1" --window-icon="/opt/NeteXt73/ikony/linux.png" --list $(grep 'href=' ./index.html | cut -d '"' -f 8 | grep $WERSJA_DISTRO | sed -e "s/-$WERSJA_DISTRO//g" -e 's/v//g' -e 's/\(.*\)./\1/' | grep -v -E "3.8.13.28" | sort -r  | awk 'ORS=NR%3?"\t\t\t":"\n"') --column="" --text="$TEXT_LISTA_KERNELI <b><span color=\"$kolor_textu\">$WERSJA_DISTRO</span></b> \n\n$TEXT_ZAZNACZ_KERNEL" --title="Kernel instalator")
-			klawisz=$?
-			if [ "$klawisz" = 0 ] && [ "$a" != "" ];then
-				a="v"$(echo $a | cut -d '|' -f 1)"-"$WERSJA_DISTRO
-				rm index.html -f; rm $PWD/v$a-$WERSJA_DISTRO -rf
-				mkdir $a; cd $a
-				pobieranie_kerneli
-				find $PWD -type f | grep -v -E "*.deb" | xargs rm -f
-				if yad --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="$TEXT_TAK:0" --button="$TEXT_POWROT:1" --text="Kernel $a $TEXT_INSTALOWAC_KERNEL"; then
-					echo $PWD > /tmp/netext73/katalog.txt
-					xterm -T instalator -e bash -c "cd $(cat /tmp/netext73/katalog.txt) && /usr/bin/yes | sudo dpkg -i *.deb && rm katalog.txt -f"
-					restart
-				else
-					echo -n "cd "$PWD" && /usr/bin/yes | sudo dpkg -i *.deb" | xclip -selection clipboard
-					yad --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEST_INSTALOWAC_KERNEL2"
-					if [ "$?" = "1" ]; then
-					      exit 1
-					fi
-				fi
-			fi
-		fi
-	#instalacja kerneli ext73
-	elif [ "$kern" != "" ] && [ "$blad" != "1" ]; then
-		if [ "$rodzaj" != "" ]; then
-			lista_kerneli
-			if [ "$klawisz" = "0" ] && [ "$blad" != "1" ] ; then
-				if [ "$(echo $a1)" = "-" ]; then
-					rm ./index.html -f; rm $a -rf
-					mkdir $a; cd $a
-					#wywołanie funkcji pobierania odpowiednich wersji kerneli
-					if [ "$premium" = "tak" ] && [ "$kernel_premium" != "tak" ]; then
-						str=""
-						strona=$(yad --center  --entry --width=$((610*$skala)) --window-icon="/opt/NeteXt73/ikony/linux.png" --title="$nazwa_skryptu" --text="$TEXT_STRONA1" --entry-text="$str" --button="gtk-ok:0" --button="$TEXT_POWROT:1")
-						klawisz=$?
-						if [ "$klawisz" = "1" ] || [ "$(echo $strona | grep '@'  | grep '@')" = "" ]; then
-							exit 1
-						elif [ "$klawisz" = "0" ]; then
-							echo $strona > ~/.netext73/kernel_premium
-							strona="$adres_glowny/kernele_premium$katalog2/"
-							export US1=$(cat ~/.netext73/kernel_premium | cut -d '@' -f 1) 
-							export PASS1=$(cat ~/.netext73/kernel_premium | cut -d '@' -f 3)
-							export kernel_premium="tak"
-							pobieranie_kerneli
-						fi
-					else
-						pobieranie_kerneli
-					fi
-					if [ "$(grep $(md5sum linux-image*) $sumy_kontrolne)" != "" ] && [ "$(grep $(md5sum linux-headers*) $sumy_kontrolne)" != "" ]; then
-						echo "nie" > /tmp/netext73/ok.txt
-						if [ -e linux-headers* ] && [ -e linux-image* ]; then
-							if yad --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="gtk-ok:0" --button="$TEXT_POWROT:1" --height=$((280*$skala)) --width=$((590*$skala)) --text="$TEST_INSTALOWAC_KERNEL3 $rodzaj $TEST_INSTALOWAC_KERNEL4\n\n$(ls *.deb)\n\n$TEXT_INSTALOWAC ?\n\n" ; then
-								naglowek > instaluj.sh
-								#sprawdz_gcc >> instaluj.sh
-								instaluj_kernel >> instaluj.sh
-								instalacja2
-								#wywalenie plików po instalacji
-								wywal_pobrane_pliki_kernela
-								restart
-							else
-								echo -n "cd $PWD" | xclip -selection clipboard
-								yad --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEST_INSTALOWAC_KERNEL5"
-							fi
-						else
-							dymek  -i $warning1 "$TEXT_UWAGA" "$TEXT_INSTALOWAC_KERNEL6"
-							blad=1
-						fi
-					else
-						yad --center --error --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0" --title="$nazwa_skryptu"  --text="$TEXT_SUMA_KONTROLNA"
-					fi
-				else
-					yad --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --title="$nazwa_skryptu"  --text="$TEXT_INSTALOWAC_KERNEL7"
+	fi
+#tylko nagłówki
+elif [ "$kern" = "$TEXT_MENU_INSTALATOR4" ]; then
+	a=$(yad --center --on-top --file-selection --filename="$download/" --title="$(echo $TEXT_DEB1 | sed 's/lub linux-image//' | sed 's/headers/headers ext73/')" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --width=$((750*$skala)) --height=$((450*$skala)) --button="gtk-ok:0" --button="$TEXT_POWROT:1")
+	if [ $? = 0 ]; then
+	if [ "$(echo $a | grep 'linux-image' | grep 'ext' | grep '.deb')" != "" ]; then
+		cd $(echo $a | sed -e 's/linux.*//g');	b=$(echo $a | sed -e 's/linux-image/linux-headers/g')
+		rm /tmp/netext73/kernel -fr; 	mkdir /tmp/netext73/kernel
+		cd /tmp/netext73/kernel;    	cp $b /tmp/netext73/kernel/
+		xterm -T instalator -e bash -c "/usr/bin/yes | sudo dpkg -i linux-headers*"
+			restart
+	elif [ "$(echo $a | grep 'linux-headers' | grep 'ext' | grep '.deb')" != "" ]; then
+		cd $(echo $a | sed -e 's/linux.*//g')
+		rm /tmp/netext73/kernel -fr; 	mkdir /tmp/netext73/kernel
+		cd /tmp/netext73/kernel;		cp $a /tmp/netext73/kernel/
+		xterm -T instalator -e bash -c "/usr/bin/yes | sudo dpkg -i linux-headers*"
+		restart
+	else
+		yad --center --error --title="$nazwa_skryptu"  --text="$(echo $TEXT_DEB1 | sed -e 's/:/!/' -e 's/lub linux-image//' -e 's/headers/headers ext73 /')" --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0"  --timeout=15
+	fi
+	fi
+#kernele PPA
+elif [ "$kern" = "$TEXT_MENU_INSTALATOR5" ]; then
+	cd /tmp/netext73; rm *.html -f
+	strona="http://kernel.ubuntu.com/~kernel-ppa/mainline/"
+	WERSJA_DISTRO=$(yad --center --on-top --title="$nazwa_skryptu" --width=$((420*$skala)) --window-icon="/opt/NeteXt73/ikony/linux.png" --text="$TEXT_PPA_1 <span color=\"$kolor_textu\">$WERSJA_UBUNTU</span>" --form --field="$TEXT_RODZAJ_SYSTEMU:CB"  "$wersje_ubu" --button="gtk-ok:0" --button="$TEXT_POWROT:1")
+	klawisz=$?; export WERSJA_DISTRO=$(echo $WERSJA_DISTRO | cut -d "|" -f 1)
+	if [ "$klawisz" = 0 ];then
+		wget $strona  2>&1 | pobieranie 
+		a=$(yad --center --height=$((630*$skala)) --width=$((410*$skala)) --button="gtk-ok:0" --button="$TEXT_POWROT:1" --window-icon="/opt/NeteXt73/ikony/linux.png" --list $(grep 'href=' ./index.html | cut -d '"' -f 8 | grep $WERSJA_DISTRO | sed -e "s/-$WERSJA_DISTRO//g" -e 's/v//g' -e 's/\(.*\)./\1/' | grep -v -E "3.8.13.28" | sort -r  | awk 'ORS=NR%3?"\t\t\t":"\n"') --column="" --text="$TEXT_LISTA_KERNELI <b><span color=\"$kolor_textu\">$WERSJA_DISTRO</span></b> \n\n$TEXT_ZAZNACZ_KERNEL" --title="Kernel instalator")
+		klawisz=$?
+		if [ "$klawisz" = 0 ] && [ "$a" != "" ];then
+			a="v"$(echo $a | cut -d '|' -f 1)"-"$WERSJA_DISTRO
+			rm index.html -f; rm $PWD/v$a-$WERSJA_DISTRO -rf
+			mkdir $a; cd $a
+			pobieranie_kerneli
+			find $PWD -type f | grep -v -E "*.deb" | xargs rm -f
+			if yad --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="$TEXT_TAK:0" --button="$TEXT_POWROT:1" --text="Kernel $a $TEXT_INSTALOWAC_KERNEL"; then
+				echo $PWD > /tmp/netext73/katalog.txt
+				xterm -T instalator -e bash -c "cd $(cat /tmp/netext73/katalog.txt) && /usr/bin/yes | sudo dpkg -i *.deb && rm katalog.txt -f"
+				restart
+			else
+				echo -n "cd "$PWD" && /usr/bin/yes | sudo dpkg -i *.deb" | xclip -selection clipboard
+				yad --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEST_INSTALOWAC_KERNEL2"
+				if [ "$?" = "1" ]; then
+					  exit 1
 				fi
 			fi
 		fi
 	fi
+#instalacja kerneli ext73
+elif [ "$kern" != "" ] && [ "$blad" != "1" ]; then
+	if [ "$rodzaj" != "" ]; then
+		lista_kerneli
+		if [ "$klawisz" = "0" ] && [ "$blad" != "1" ] ; then
+			if [ "$(echo $a1)" = "-" ]; then
+				rm ./index.html -f; rm $a -rf
+				mkdir $a; cd $a
+				#wywołanie funkcji pobierania odpowiednich wersji kerneli
+				if [ "$premium" = "tak" ] && [ "$kernel_premium" != "tak" ]; then
+					str=""
+					strona=$(yad --center  --entry --width=$((610*$skala)) --window-icon="/opt/NeteXt73/ikony/linux.png" --title="$nazwa_skryptu" --text="$TEXT_STRONA1" --entry-text="$str" --button="gtk-ok:0" --button="$TEXT_POWROT:1")
+					klawisz=$?
+					if [ "$klawisz" = "1" ] || [ "$(echo $strona | grep '@'  | grep '@')" = "" ]; then
+						exit 1
+					elif [ "$klawisz" = "0" ]; then
+						echo $strona > ~/.netext73/kernel_premium
+						strona="$adres_glowny/kernele_premium$katalog2/"
+						export US1=$(cat ~/.netext73/kernel_premium | cut -d '@' -f 1) 
+						export PASS1=$(cat ~/.netext73/kernel_premium | cut -d '@' -f 3)
+						export kernel_premium="tak"
+						pobieranie_kerneli
+					fi
+				else
+					pobieranie_kerneli
+				fi
+				if [ "$(grep $(md5sum linux-image*) $sumy_kontrolne)" != "" ] && [ "$(grep $(md5sum linux-headers*) $sumy_kontrolne)" != "" ]; then
+					echo "nie" > /tmp/netext73/ok.txt
+					if [ -e linux-headers* ] && [ -e linux-image* ]; then
+						if yad --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="gtk-ok:0" --button="$TEXT_POWROT:1" --height=$((280*$skala)) --width=$((590*$skala)) --text="$TEST_INSTALOWAC_KERNEL3 $rodzaj $TEST_INSTALOWAC_KERNEL4\n\n$(ls *.deb)\n\n$TEXT_INSTALOWAC ?\n\n" ; then
+							naglowek > instaluj.sh
+							#sprawdz_gcc >> instaluj.sh
+							instaluj_kernel >> instaluj.sh
+							instalacja2
+							#wywalenie plików po instalacji
+							wywal_pobrane_pliki_kernela
+							restart
+						else
+							echo -n "cd $PWD" | xclip -selection clipboard
+							yad --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEST_INSTALOWAC_KERNEL5"
+						fi
+					else
+						dymek  -i $warning1 "$TEXT_UWAGA" "$TEXT_INSTALOWAC_KERNEL6"
+						blad=1
+					fi
+				else
+					yad --center --error --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0" --title="$nazwa_skryptu"  --text="$TEXT_SUMA_KONTROLNA"
+				fi
+			else
+				yad --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --title="$nazwa_skryptu"  --text="$TEXT_INSTALOWAC_KERNEL7"
+			fi
+		fi
+	fi
+fi
diff --git a/procedury b/procedury
--- a/procedury
+++ b/procedury
@@ -11,10 +11,10 @@
 #		   				| |\  |  __/ |_  __//  \| |_    / /  ___) |
 #		   				|_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
 #
-#  __  ___ _______   ____ __  __  _   _ ___  __ _____ __  ___    ____   __ __ _____ ___ __ __ _  _ 
+#  __  ___ _______   ____ __  __  _   _ ___  __ _____ __  ___    ____   __ __ _____ ___ __ __ _  _
 # /__\| _,\_   _\ `v' /  V  |/  \| | | |_  |/  \_   _/__\| _ \ /' _| `v' /' _/_   _| __|  V  | || |
 #| \/ | v_/ | |  `. .'| \_/ | /\ | |_| |/ /| /\ || || \/ | v / `._`.`. .'`._`. | | | _|| \_/ | \/ |
-# \__/|_|   |_|   !_! |_| |_|_||_|___|_|___|_||_||_| \__/|_|_\ |___/ !_! |___/ |_| |___|_| |_|\__/ 
+# \__/|_|   |_|   !_! |_| |_|_||_|___|_|___|_||_||_| \__/|_|_\ |___/ !_! |___/ |_| |___|_| |_|\__/
 #
 #            __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
 #       ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
@@ -98,10 +98,10 @@ export WERSJA_UBUNTU="$(lsb_release -cs)"
 export NR_WERSJA_UBUNTU="$(lsb_release -rs)"
 case `lsb_release -cs` in
 	qiana|rebecca|rafaela|freya|rosa)
-		export WERSJA_UBUNTU="trusty" 
+		export WERSJA_UBUNTU="trusty"
 		export NR_WERSJA_UBUNTU="14.04" ;;
 	sarah)
-		export WERSJA_UBUNTU="xenial" 
+		export WERSJA_UBUNTU="xenial"
 		export NR_WERSJA_UBUNTU="16.04" ;;
 esac
 
@@ -124,7 +124,7 @@ fi
 if [ "$(uname -m)" = "x86_64" ]; then
 	bit="64bit"
 	bit2="amd64"
-else 
+else
 	yad --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/netext.png" --button="gtk-ok:0" --title="$nazwa_skryptu"  --text="$TEXT_STEROWNIKI1"
 	exit 1
 fi
@@ -280,7 +280,7 @@ if [ "$(cat /proc/cpuinfo | grep Intel)" != "" ]; then
 else
 	echo "sudo apt-get install amd64-microcode"  >> instaluj.sh
 fi
-instalacja 
+instalacja
 }
 
 microcode_usun(){
@@ -353,7 +353,7 @@ elif [ "$apmik" = "nowy" ]; then
 	sudo chown root:root /etc/systemd/system/hibernate.target.wants/*
 	sudo chown root:root /etc/systemd/system/hybrid-sleep.target.wants/*
 	sudo chown root:root /etc/systemd/system/suspend.target.wants/*
-	sudo sed -i 's/\/sbin\/wpa_cli suspend/\/etc\/apm-ext73\/apm_before/g' /lib/systemd/system-sleep/wpasupplicant 
+	sudo sed -i 's/\/sbin\/wpa_cli suspend/\/etc\/apm-ext73\/apm_before/g' /lib/systemd/system-sleep/wpasupplicant
 	sudo sed -i 's/\/usr\/lib\/pm-utils\/power.d\/95hdparm-apm resume/echo 1 > \/dev\/null/g' /lib/systemd/system-sleep/hdparm
 
 	#udev jeżeli notebook
@@ -389,8 +389,8 @@ elif [ "$apmik" = "nowy" ]; then
 fi
 sudo chown root:root /usr/lib/pm-utils/power.d/*
 if [ "$(which journalctl)" != "" ] && [ "$(journalctl -u cron | grep systemd)" != "" ];then
-	sudo systemctl disable ondemand 2> /dev/null 
-	sudo systemctl stop ondemand 2> /dev/null 
+	sudo systemctl disable ondemand 2> /dev/null
+	sudo systemctl stop ondemand 2> /dev/null
 	sudo chmod a-x /etc/init.d/ondemand
 else
 	sudo service ondemand stop
@@ -472,7 +472,7 @@ fi
 #intel turbo bateria
 if [ "$(cat ~/.netext73/apm_status | grep turbo_batt_on | grep FALSE)" = "" ];then
 	sudo sed -i 's/echo 1 > \$batintel/echo 0 > \$batintel/g' $katalog_apm
-	
+
 else
 	sudo sed -i 's/echo 0 > \$batintel/echo 1 > \$batintel/g' $katalog_apm
 fi
@@ -668,11 +668,11 @@ if [ "$apmik" = "stary" ]; then
 		fi
 	fi
 
-	if [ "$(ls /etc/pm/power.d/ | wc -l)" != "6" ] || [ $( ls /usr/lib/pm-utils/power.d/ -la | grep rwxr | grep -v drwxr-xr-x | wc -l) != "2" ]; then 
+	if [ "$(ls /etc/pm/power.d/ | wc -l)" != "6" ] || [ $( ls /usr/lib/pm-utils/power.d/ -la | grep rwxr | grep -v drwxr-xr-x | wc -l) != "2" ]; then
 		stan_apm="-"
 	fi
 elif [ "$apmik" = "nowy" ]; then
-	
+
 	if [ -e /etc/apm-ext73/ ] && [ "$(ls /etc/apm-ext73/ | wc -l)" != "11" ] || [ "$twoj_apm" != "$wersja_apm" ] ; then
 		stan_apm="-"
 	else
@@ -782,7 +782,7 @@ stan_apm_config(){
 	else
 		export vsync_on="TRUE"
 	fi
-	
+
 	#stan samsung
 	if [ "$(cat $katalog_apm | grep -e "#.*samsung_laptop")" != "" ]; then
 		export stan_samsung="FALSE"
@@ -796,7 +796,7 @@ stan_apm_config(){
 	else
 		export jasnosc_dziala="FALSE"
 	fi
-	
+
 	export jasnosc_dziala_przed=$jasnosc_dziala
 	export wifi_n_on_przed=$wifi_n_on
 	export wifi_batt_fix_przed=$wifi_batt_fix
@@ -810,7 +810,7 @@ stan_apm_config(){
 	export hibernacja_menu_przed=$hibernacja_menu
 	export vsync_on_przed=$vsync_on
 	export stan_samsung_przed=$stan_samsung
-	
+
 	#wysłanie danych do configu
 	if [ "$1" = "czeki" ]; then
 		if [ "$apmik" = "stary" ]; then
@@ -954,7 +954,7 @@ fi
 else
 	#tu zmienić
 	echo $kern > ~/.netext73/instalator_kerneli #zapamiętanie wybranego kernela
-	if [ "$premium" = "tak" ]; then 
+	if [ "$premium" = "tak" ]; then
 		if [ "$kernel_premium" = "tak" ]; then
 			strona="$adres_glowny/kernele_premium$katalog2/"
 		fi
@@ -1225,7 +1225,7 @@ echo "sudo update-grub"
 restart(){
 yad --center --on-top --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="$TEXT_TAK:0" --button="$TEXT_NIE:1" --text="$TEXT_RESTART"
 	if [ $? = 0 ]; then
-		#cd /opt/NeteXt73 && ./NeteXt73_root 
+		#cd /opt/NeteXt73 && ./NeteXt73_root
 		reboot
 	fi
 }
@@ -1371,7 +1371,7 @@ if [ "$USER" != "root" ];then
 		notify-send "$1" "$2" "$3" "$4"
 	elif [ "$(which kdialog)" != "" ];then
 		kdialog --title "$3" -passivepopup "$4"
-	else	
+	else
 		yad --center --on-top --info --title="$3"  --window-icon="$2" --image="$2" --text="$4" --timeout=5 --geometry="$((300*$skala))x$((100*$skala))+15+30" --no-buttons --undecorated &
 	fi
 elif [ "$USER" = "root" ];then
@@ -1418,21 +1418,21 @@ yad_wget(){
 #
 # LICENSE:      GNU GPLv3 (http://www.gnu.de/documents/gpl-3.0.en.html)
 #
-# NOTICE:       THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW. 
-#               EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES 
-#               PROVIDE THE PROGRAM “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR 
-#               IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY 
-#               AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND 
+# NOTICE:       THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW.
+#               EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES
+#               PROVIDE THE PROGRAM “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR
+#               IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
+#               AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND
 #               PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE,
 #               YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.
 #
-#               IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY 
-#               COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS THE PROGRAM AS 
-#               PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, 
-#               INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE 
-#               THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED 
-#               INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE 
-#               PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER 
+#               IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY
+#               COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS THE PROGRAM AS
+#               PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL,
+#               INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE
+#               THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED
+#               INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE
+#               PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER
 #               PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 #
 # USAGE:        yad_wget <space-delimited URLs>
@@ -1490,7 +1490,7 @@ COUNTER="1"
 DYNAMIC_COUNTER="1"
 
 # main
-# iterate through all URIs, download them in the background and 
+# iterate through all URIs, download them in the background and
 # pipe all output simultaneously to yad
 # source: http://pastebin.com/yBL2wjaY
 
@@ -1506,13 +1506,13 @@ for URI in $URILIST; do
 	COUNTER="$[$COUNTER+1]"                 # increment counter
 done | yad --center --on-top --multi-progress --auto-kill --auto-close --width=$((700*$skala)) $YADBARS --title "$nazwa_skryptu" \
 --text "<b>$TEXT_POB2</b>" --window-icon="/opt/NeteXt73/ikony/download.png" --image="/opt/NeteXt73/ikony/download.png" --button="$TEXT_ZAMKNIJ:1"
-# ↑ launch yad multi progress-bar window 
+# ↑ launch yad multi progress-bar window
 }
 
 procesor_monitor(){
 barek="--bar="" --bar="$(free -m | awk '{print $1}' | head -n 1)" --bar="$(free -m | awk '{print $2}' | head -n 1)" --bar="$(free -m | awk '{print $3}' | head -n 1)" --bar="$(free -m | awk '{print $4}' | head -n 1)" --bar="$(free -m | awk '{print $5}' | head -n 1)" --bar="$(free -m | awk '{print $6}' | head -n 1)" --bar=swap --bar="""
 for i in $(seq 1 $(grep 'model name' /proc/cpuinfo | wc -l )); do
-	barek="$barek --bar=$(echo "core"$i"")" 
+	barek="$barek --bar=$(echo "core"$i"")"
 done
 petla_duza="tak"
 
@@ -1540,12 +1540,12 @@ while [ "$petla_duza" = "tak" ]; do
 	echo "9:#C P U      C O R E     F R E Q U E N C Y"
 	sleep 1
 	for i in $(seq 10 $(($(grep 'model name' /proc/cpuinfo | wc -l )+9))); do
-		echo "$i:$(($(cat /proc/cpuinfo | grep MHz | cut -d ' ' -f 3 | sed -n $(($i-9))'p' | sed 's/\..*//' )/60))" # * 6000MHZ/100 
+		echo "$i:$(($(cat /proc/cpuinfo | grep MHz | cut -d ' ' -f 3 | sed -n $(($i-9))'p' | sed 's/\..*//' )/60))" # * 6000MHZ/100
 		echo "$i:#$(cat /proc/cpuinfo | grep MHz | cut -d ' ' -f 3 | sed -n $(($i-9))'p' | sed 's/\..*//' ) MHz"
-	done 
+	done
 done | yad --title "$nazwa_skryptu" --center --multi-progress $barek --text="$(cat /proc/cpuinfo | grep 'model name' | head -n 1 | sed 's/.*: //')\n\n" --auto-kill --on-top --window-icon="/opt/NeteXt73/ikony/monitor.png" --image="/opt/NeteXt73/ikony/monitor.png" --width=$((460*$skala)) --button="$TEXT_ZAMKNIJ:1"
 if [ "$?" != "" ]; then
-	petla_duza="nie"  
+	petla_duza="nie"
 fi
 }
 
@@ -1671,14 +1671,14 @@ kill_process(){
 petla="tak"
 while [ $petla = "tak" ]; do
 	process=$(ps -u $USER | yad --center --list --title="$nazwa_skryptu" --window-icon="process-stop" --image="process-stop" --buttons-layout=center --column "$TEXT_SELECT_TO_KILL" --text="$TEXT_LISTA_PROCESOW $USER $TEXT_PROCESY" --width $((450*$skala)) --height $((450*$skala)) --button="gtk-ok:0" --button="$TEXT_ZAMKNIJ:1" --on-top )
-	ans=$(echo $?) 
-	if test "$ans" -eq "0"; then 
+	ans=$(echo $?)
+	if test "$ans" -eq "0"; then
 		select=$(echo $process | cut -d" " -f1)
 		kill $select # 2> /dev/null
-	fi 
-	
-	if test "$ans" -eq "1"; then 
-		petla="nie" 
+	fi
+
+	if test "$ans" -eq "1"; then
+		petla="nie"
 	fi
 done
 }
