poprawki tłumaczeń

diff --git a/NeteXt73 b/NeteXt73
--- a/NeteXt73
+++ b/NeteXt73
@@ -57,17 +57,18 @@ fi
 sumy(){
 #pobranie sum kontrolnych i sprawdzanie połączenia z netem
 cd /tmp
+
+wget $adres_sum_kontrolnych  2>&1 | pobieranie
+mv sumy.txt $sumy_kontrolne
+if [ "$(cat $sumy_kontrolne)" = "" ]; then
+	yad --center --info --title="$nazwa_skryptu  " --text="<span color=\"$kolor_textu\"><b>$BRAKNETA</b></span>" --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0" --on-top
+	exit 1
+fi
 if [ "$(curl $adres_sum_kontrolnych2)" != 'OK' ]; then
 	yad --center --info --title="$nazwa_skryptu   " --text="<span color=\"$kolor_textu\"><b>$BRAKNETA</b></span>" --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0" --on-top
 	exit 1
-else
-	wget $adres_sum_kontrolnych  2>&1 | pobieranie
-	mv sumy.txt $sumy_kontrolne
-	if [ "$(cat $sumy_kontrolne)" = "" ]; then
-		yad --center --info --title="$nazwa_skryptu  " --text="<span color=\"$kolor_textu\"><b>$BRAKNETA</b></span>" --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0" --on-top
-		exit 1
-	fi
 fi
+
 
 #naprawa Gtk-WARNING **: Theme file for default has no directories
 if [ "$(grep gtk-fallback-icon-theme="default" ~/.gtkrc-2.0)" != "" ]; then
